### ISSUE TITLE
Nice tool and test samples to try, but more documents

### ISSUE THREAD

**Issue by hotblast** [nsgrantham/fungi-identify#1]
In order to test, i would need to know the file format of S.csv, X.csv, and Y. csv, and which files were used for converting S.X.Y.csv from https://figshare.com/articles/1000homes/1270900.
Thanks

This fills the subdirectory data with S.csv (lon, lat coordinates of each home), X.csv (covariate info for each home), and Y.csv (presence/absence of taxa per home). A further subdirectory raw is created that holds the pre-munged txt, biom, and fa data files.

**Comment by nsgrantham** [comment]
Hello, I updated the code in `get-data.R`, which downloads the raw data files from Figshare and prepares them for analysis. I have also added `S.csv` and `X.csv` to the `data` directory, along with versions of the OTU table and taxonomy as `Y-reduced.csv` and `tax-reduced.csv`. The full data files were too large to include here, these reduced files contain 10% of the total number of OTUs (about 5k from the original 50k). Hope this helps!
